#!/bin/bash
# SUPREME ULTRA V2
# The Supreme Team https://github.com/SupremePi/

sb_version="Supreme ToolKit Version 2"
sb_toolkit=/home/pi/.supreme_toolkit/sb_toolkit
rp_menu=/home/pi/RetroPie/retropiemenu
sb_menu=$sb_toolkit/retropiemenu
#sb_menu_pi3=$sb_toolkit/retropiemenu-pi3
rpi=$(cat /proc/device-tree/model |awk '{print $3}')
STV=$(cat /proc/cpuinfo)
STR=$(cat /proc/cpuinfo | grep Serial | cut -d ' ' -f 2)
currentuser=$(whoami) # Check user

# [rpi_model] Examples: # Raspberry Pi Zero 2 W Rev 1.0 # Raspberry Pi 3 Model B Plus Rev 1.3  # Raspberry Pi 2 Model B Rev 1.1
rpi_model=$(tr -d '\0' 2>/dev/null < /proc/device-tree/model) 
if [[ "$rpi_model" == "Raspberry Pi Zero 2"* ]] || [[ "$rpi_model" == "Raspberry Pi 3"* ]] || [[ "$rpi_model" == "Raspberry Pi 2"* ]]; then
	rpi=3
	sb_menu=$sb_toolkit/retropiemenu-pi3
fi
